### ISSUE TITLE
Can´t set values in doInit

### ISSUE THREAD

**Issue by FayaX-PT** [rapsacnz/MultiColSelect#1]
Hello!

I am using your component, but I cant set the list by code in doInit method.
I am using this code:

```
....
 for(var i = 0; i < returnedValues.length; i++){
                    employeesData.push({
                        "label": returnedValues[i].Id,
                        "value": returnedValues[i].Name
                    });  
                }
                        	    
                component.set("v.employees", employeesData); 
...
```

this componnet only works with defaults values?

Thank you!

**Comment by rapsacnz** [comment]
If you want to set data to the component dynamically, you will need to add a change handler to the list.

I'm assuming you are doing this from outside the component - injecting more values for example.

Say I was wanting to add a list of stagenames to the select, from the parent component, I would do something like this:

        var data = component.get("v.stagenames"); 
        data.push({ "label": "test1",  "value": "test1" }); 
        component.set("v.stagenames", data); 

Assuming that the multicol select was bound to this stagenames list - eg:

      <c:MultiColSelect fieldName="Opportunity Stage" allValues="{!v.stagenames}" selectedValues="{!v.stagename}"  />

Then I would need to add just one line to the component markup:

    <aura:handler name="change" value="{!v.allValues}" action="{!c.doInit}"/>

This handler would listen for changes to this list and would reinit the component if necessary.

**Comment by FayaX-PT** [comment]
Thank you! it Works :)
It would be nice if you add this line to your code as well :)

**Comment by rapsacnz** [comment]
There is a small problem there - if I have it as standard, lightning gives me a warning for making the iteration render twice in the same display cycle... so you need to choose whether to have a static list or a dynamic one feeding your picker. I have updated the readme to mention this.
