### ISSUE TITLE
Loss of elements

### ISSUE THREAD

**Issue by FayaX-PT** [rapsacnz/MultiColSelect#2]
Hello!

If I move the elements in a quick way, some value are lost, and onother ones are duplicated.
I suppose that it insn't normal.

Thank you.

**Comment by rapsacnz** [comment]
I'll have a look at this tomorrow. If you are trying to debug - check that the index value for each item is being set.

**Comment by rapsacnz** [comment]
I'm worried that it might be linked to the slowness of Locker Service causing issues (sorts are not completing before next drop perhaps). However I haven't been able to reliably pinpoint the issue yet. Still looking.

I was able to come up with a solution to the slowness in this sfse question: https://salesforce.stackexchange.com/questions/180922/api-v40-slows-down-apex-generated-data-in-lightning-components/181046#181046
 
I could do this in the app if necessary too (basically storing everything as serialized strings - you'd think slow, but it's a lot times faster than Locker Service)

**Comment by dineshsm** [comment]
Hello,
    Am having same problem values are duplicated, can you help me here ? @rapsacnz

**Comment by rapsacnz** [comment]
I will have some to investigate this next week (will try the solution that I mentioned above)

**Comment by rapsacnz** [comment]
I just tried a serialized string version and it didn't help. I also don't think it's a speed issue, as every action only takes around 10ms. I'm looking at some other solutions.

**Comment by rapsacnz** [comment]
Hi @dineshsm @FayaX-PT, I've spent time trying to fix this issue, but in the end I decided I was easier to make a new, better one - I'm deprecating this component in favour of my new one here: https://github.com/rapsacnz/DualSelect - sorry for the inconvenience.
